package project__3;

import java.util.Arrays;

public class Project3 {
	public static void main(String args[]){
		StopWatch s = new StopWatch();
		int[] randomInts1 = ArrayUtil.randomIntArray(10000, 10000);
		int[] randomInts2 = ArrayUtil.randomIntArray(20000, 20000);
		int[] randomInts3 = ArrayUtil.randomIntArray(30000, 30000);
		int[] randomInts4 = ArrayUtil.randomIntArray(40000, 40000);
		int[] randomInts5 = ArrayUtil.randomIntArray(50000, 50000);
		int[] randomInts6 = ArrayUtil.randomIntArray(60000, 60000);
		int[] smallInts = ArrayUtil.randomIntArray(5, 10);
		double[] smallDoubles = ArrayUtil.randomDoubleArray(5, 10);
		double[] smallDoubles1 = smallDoubles;
		double[] smallDoubles2 = smallDoubles;
		System.out.println(Arrays.toString(smallInts));
		System.out.println(Arrays.toString(smallDoubles));
		System.out.println(Arrays.toString(smallDoubles1));
		System.out.println(Arrays.toString(smallDoubles2));
		System.out.println();
		s.start();
		BubbleSorter.sort(smallInts);
		s.stop();
		System.out.println("Bubble int: Length: "+ smallInts.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
		s.reset();
		s.start();
		BubbleSorter.sort(smallDoubles);
		s.stop();
		System.out.println("Bubble: Length: "+ smallDoubles.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
		s.reset();
		s.start();
		SelectionSorter.sort(smallInts);
		s.stop();
		System.out.println("Selection int: Length: "+ smallInts.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
		s.reset();
		s.start();
		SelectionSorter.sort(smallDoubles1);
		s.stop();
		System.out.println("Selection: Length: "+ smallDoubles.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
		s.reset();
		s.start();
		MergeSorter.sort(smallInts);
		s.stop();
		System.out.println("Merge int: Length: "+ smallInts.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
		s.reset();
		s.start();
		MergeSorter.sort(smallDoubles2);
		s.stop();
		System.out.println("Merge: Length: "+ smallDoubles.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
		s.reset();
		System.out.println(Arrays.toString(smallInts));
		System.out.println(Arrays.toString(smallDoubles));
		System.out.println(Arrays.toString(smallDoubles1));
		System.out.println(Arrays.toString(smallDoubles2));
	}
//	public static void meh(){
//		s.start();
//		BubbleSorter.sort(randomInts1);
//		s.stop();
//		System.out.println("Bubble: Length: "+ randomInts1.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		SelectionSorter.sort(randomInts1);
//		s.stop();
//		System.out.println("Selection: Length: "+ randomInts1.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		MergeSorter.sort(randomInts1);
//		s.stop();
//		System.out.println("Merge: Length: "+ randomInts1.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		System.out.println();
//		s.start();
//		BubbleSorter.sort(randomInts2);
//		s.stop();
//		System.out.println("Bubble: Length: "+ randomInts2.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();		
//		s.start();
//		SelectionSorter.sort(randomInts2);
//		s.stop();
//		System.out.println("Selection: Length: "+ randomInts2.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		MergeSorter.sort(randomInts2);
//		s.stop();
//		System.out.println("Merge: Length: "+ randomInts2.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		System.out.println();
//		s.start();
//		BubbleSorter.sort(randomInts3);
//		s.stop();
//		System.out.println("Bubble: Length: "+ randomInts3.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		SelectionSorter.sort(randomInts3);
//		s.stop();
//		System.out.println("Selection: Length: "+ randomInts3.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		MergeSorter.sort(randomInts3);
//		s.stop();
//		System.out.println("Merge: Length: "+ randomInts3.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		System.out.println();
//		s.start();
//		BubbleSorter.sort(randomInts4);
//		s.stop();
//		System.out.println("Bubble: Length: "+ randomInts4.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		SelectionSorter.sort(randomInts4);
//		s.stop();
//		System.out.println("Selection: Length: "+ randomInts4.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		MergeSorter.sort(randomInts4);
//		s.stop();
//		System.out.println("Merge: Length: "+ randomInts4.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		System.out.println();
//		s.start();
//		BubbleSorter.sort(randomInts5);
//		s.stop();
//		System.out.println("Bubble: Length: "+ randomInts5.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		SelectionSorter.sort(randomInts5);
//		s.stop();
//		System.out.println("Selection: Length: "+ randomInts5.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		MergeSorter.sort(randomInts5);
//		s.stop();
//		System.out.println("Merge: Length: "+ randomInts5.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		System.out.println();
//		s.start();
//		BubbleSorter.sort(randomInts6);
//		s.stop();
//		System.out.println("Bubble: Length: "+ randomInts6.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		SelectionSorter.sort(randomInts6);
//		s.stop();
//		System.out.println("Selection: Length: "+ randomInts6.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//		s.start();
//		MergeSorter.sort(randomInts6);
//		s.stop();
//		System.out.println("Merge: Length: "+ randomInts6.length + ",   \tMilliseconds Elapsed: " + s.getMilliSecondsElapsed());
//		s.reset();
//	}

}
